apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap
  namespace: backend
data:
  SERVICE_PORT: "8087"
  JAEGER_ENDPOINT: "http://jaeger-collector.istio-system.svc.cluster.local:14268/api/traces"
  LOKI_ENDPOINT: "http://loki.istio-system.svc.cluster.local:3100/api/prom/push"